// pipeline {
//     agent any
//     options {
//         skipStagesAfterUnstable()
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'mvn test'
//             }
//             post {
//                 always {
//                     junit 'target/surefire-reports/*.xml'
//                 }
//             }
//         }
//         stage('Deliver') { 
//             steps {
//                 sh './jenkins/scripts/deliver.sh' 
//             }
//         }
//     }
// }


// pipeline{
//     agent any

//     tools{
//         maven 'mymaven'
//     }

//     stages{
//         stage('build')
//         {
//             steps{
//                 echo "this is the build stage"
//                 sh "mvn clean package"
//             }
//         }
//         stage('test')
//         {
//             steps{
//                 echo "this is the test stage"
//                 sh "mvn test"
//             }
//         }
//         // stage('deploy')
//         // {
//         //     steps{
//         //         echo "This is the deploy stage"
//         //     }
//         // }
//     }
// }



pipeline{
    agent any

    tools{
        maven 'mymaven'
    }

    parameters{
        choice(name : 'VERSION' , choices:['1.1.0', '1.2.0'], description :'Choose Version')
        booleanParam(name: 'executeTasks', defaultValue:true, description:'')
    }

    stages{
        stage('build')
        {
            echo "Build Iniated"
            sh "mvn clean package"
        }

        stage('test'){
            when{
                expression{
                    params.executeTasks == true
                }
            }

            steps{
                echo "Tests iniated"
                sh "mvn test"
            }
        }
    }
}